#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# MindooDB Server — Interactive Setup
#
# Run from the repository root:
#   bash setup.sh
#
# The script builds the Docker image, creates the data directory and password
# file, initialises the server identity (with optional system admin creation),
# and writes a docker-compose.override.yml when non-default values are chosen.
# ---------------------------------------------------------------------------

DOCKER_IMAGE="mindoodb-server"
DOCKERFILE="src/node/server/Dockerfile"
DEFAULT_SERVER_NAME="server1"
DEFAULT_DATA_DIR="../mindoodb-data"
DEFAULT_BIND_ADDR="0.0.0.0"
DEFAULT_PORT="1661"

# ── helpers ───────────────────────────────────────────────────────────────────

banner() {
  echo ""
  echo "============================================================"
  echo "  $1"
  echo "============================================================"
}

info()  { echo "  ▸ $*"; }
error() { echo "  ✗ $*" >&2; }

prompt_default() {
  local prompt="$1" default="$2" var_name="$3"
  printf "  %s [%s]: " "$prompt" "$default"
  read -r value
  eval "$var_name=\"\${value:-$default}\""
}

prompt_password() {
  local prompt="$1" var_name="$2"
  while true; do
    printf "  %s: " "$prompt"
    read -rs password
    echo ""
    if [[ -z "$password" ]]; then
      error "Password cannot be empty."
      continue
    fi
    printf "  Confirm password: "
    read -rs password_confirm
    echo ""
    if [[ "$password" != "$password_confirm" ]]; then
      error "Passwords do not match. Try again."
      continue
    fi
    eval "$var_name=\"\$password\""
    return
  done
}

# ── preflight ─────────────────────────────────────────────────────────────────

banner "MindooDB Server — Interactive Setup"

if ! command -v docker &>/dev/null; then
  error "Docker is not installed or not in PATH."
  error "Install Docker first: https://docs.docker.com/get-docker/"
  exit 1
fi
info "Docker found: $(docker --version)"

if [[ ! -f "$DOCKERFILE" ]]; then
  error "Cannot find $DOCKERFILE — run this script from the MindooDB repository root."
  exit 1
fi

# ── prompts ───────────────────────────────────────────────────────────────────

banner "Configuration"

prompt_default "Server name" "$DEFAULT_SERVER_NAME" SERVER_NAME
prompt_password "Server unlock password" SERVER_PASSWORD
prompt_default "Data directory" "$DEFAULT_DATA_DIR" DATA_DIR
prompt_default "Bind address (0.0.0.0 = all interfaces)" "$DEFAULT_BIND_ADDR" BIND_ADDR

DATA_DIR_ABS="$(cd "$(dirname "$DATA_DIR")" 2>/dev/null && pwd)/$(basename "$DATA_DIR")" || DATA_DIR_ABS="$DATA_DIR"
SERVER_DATA="$DATA_DIR/server"
PASSWORD_FILE="$DATA_DIR/.server_unlock"
IDENTITY_FILE="$SERVER_DATA/server-identity.json"

echo ""
info "Server name:    $SERVER_NAME"
info "Data directory: $DATA_DIR"
info "Bind address:   $BIND_ADDR:$DEFAULT_PORT"
echo ""

# ── guard against re-init ─────────────────────────────────────────────────────

if [[ -f "$IDENTITY_FILE" ]]; then
  echo ""
  printf "  Server identity already exists at %s.\n" "$IDENTITY_FILE"
  printf "  Overwrite? (y/N): "
  read -r overwrite
  if [[ "${overwrite,,}" != "y" ]]; then
    info "Aborted. Existing identity kept."
    exit 0
  fi
  FORCE_FLAG="--force"
else
  FORCE_FLAG=""
fi

# ── create data directory and password file ───────────────────────────────────

banner "Creating data directory"

mkdir -p "$SERVER_DATA"
info "Created $SERVER_DATA"

printf '%s' "$SERVER_PASSWORD" > "$PASSWORD_FILE"
chmod 600 "$PASSWORD_FILE"
info "Password written to $PASSWORD_FILE (mode 600)"

# ── build docker image ────────────────────────────────────────────────────────

banner "Building Docker image"

docker build -f "$DOCKERFILE" -t "$DOCKER_IMAGE" .

info "Image $DOCKER_IMAGE built successfully."

# ── initialise server identity ────────────────────────────────────────────────

banner "Initialising server identity"

info "The server password is read from the mounted file."
info "You will be prompted to create a system admin interactively."
echo ""

docker run --rm -it \
  -v "$(pwd)/$SERVER_DATA:/data" \
  -v "$(pwd)/$PASSWORD_FILE:/run/secrets/server_unlock:ro" \
  -e MINDOODB_SERVER_PASSWORD_FILE=/run/secrets/server_unlock \
  --entrypoint node \
  "$DOCKER_IMAGE" dist/node/server/serverinit.js --data-dir /data --name "$SERVER_NAME" $FORCE_FLAG

# ── generate docker-compose.override.yml if needed ────────────────────────────

NEEDS_OVERRIDE=false

if [[ "$DATA_DIR" != "$DEFAULT_DATA_DIR" ]] || [[ "$BIND_ADDR" != "$DEFAULT_BIND_ADDR" ]]; then
  NEEDS_OVERRIDE=true
fi

if $NEEDS_OVERRIDE; then
  banner "Writing docker-compose.override.yml"

  cat > docker-compose.override.yml <<OVERRIDE_EOF
# Generated by setup.sh — customises paths and bind address.
# docker compose merges this with docker-compose.yml automatically.
services:
  mindoodb:
    volumes:
      - ${DATA_DIR}/server:/data
      - ${DATA_DIR}/.server_unlock:/run/secrets/server_unlock:ro
    ports:
      - "${BIND_ADDR}:${DEFAULT_PORT}:${DEFAULT_PORT}"
OVERRIDE_EOF

  info "Override written to docker-compose.override.yml"
fi

# ── summary ───────────────────────────────────────────────────────────────────

banner "Setup complete"

echo ""
info "Server name:       $SERVER_NAME"
info "Data directory:    $DATA_DIR/server"
info "Password file:     $PASSWORD_FILE"
info "Bind address:      $BIND_ADDR:$DEFAULT_PORT"
info "Docker image:      $DOCKER_IMAGE"
if $NEEDS_OVERRIDE; then
  info "Override file:     docker-compose.override.yml"
fi
echo ""
echo "  Next steps:"
echo ""
echo "    # Start the server"
echo "    docker compose up -d"
echo ""
echo "    # Check health"
echo "    curl http://${BIND_ADDR}:${DEFAULT_PORT}/health"
echo ""
echo "    # View logs"
echo "    docker compose logs -f"
echo ""
echo "    # Stop the server"
echo "    docker compose down"
echo ""
